---
# tasks file for snmp
- name: add OS specific variables
  include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | replace(' ', '_') }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - "defaults.yml"
      paths:
        - "vars"
  loop_control:
    loop_var: loop_vars

- name: include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: include distribution tasks
  include_tasks: "{{ loop_distribution }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | replace(' ', '_') }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - "defaults.yml"
      paths:
        - "tasks"
  loop_control:
    loop_var: loop_distribution
  tags: always

- name: include download files task
  include_tasks: tasks/download_files.yml
  tags: always

- name: include product_serial
  include_tasks: tasks/product_serial_permissions.yml
  tags: always

